# Generated by Django 6.0.2 on 2026-02-17 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ps_limit', models.CharField(max_length=100)),
                ('crime_number', models.CharField(max_length=100)),
                ('section_of_law', models.CharField(max_length=200)),
                ('date_of_occurrence', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('complainant_name', models.CharField(max_length=200)),
                ('accused_details', models.TextField()),
                ('gist_of_case', models.TextField()),
                ('current_stage', models.CharField(choices=[('UI', 'Under Investigation'), ('PT', 'Pending Trial'), ('HC', 'Pending before High Court'), ('SC', 'Pending before Supreme Court')], max_length=2)),
                ('action_to_be_taken', models.TextField()),
                ('date_of_first_updation', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(max_length=10)),
                ('case_holding_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
