# Generated by Django 6.0.2 on 2026-02-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='current_stage',
            field=models.CharField(choices=[('UI', 'Under Investigation'), ('PT', 'Pending Trial'), ('HC', 'Pending before High Court'), ('SC', 'Pending before Supreme Court'), ('CC', 'Case Closed')], default='UI', max_length=2),
        ),
    ]
